version: '3'
services:
  # spark-master:
  #   image: bde2020/spark-master:3.2.0-hadoop3.2
  #   container_name: spark-master
  #   ports:
  #     - "8080:8080"
  #     - "7077:7077"
  #   environment:
  #     - INIT_DAEMON_STEP=setup_spark
  # spark-worker-1:
  #   image: bde2020/spark-worker:3.2.0-hadoop3.2
  #   container_name: spark-worker-1
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
  # spark-history-server:
  #     image: bde2020/spark-history-server:3.2.0-hadoop3.2
  #     container_name: spark-history-server
  #     depends_on:
  #       - spark-master
  #     ports:
  #       - "18081:18081"
  #     volumes:
  #       - /tmp/spark-events-local:/tmp/spark-events
  jupyter-notebook:
      image: jupyter/pyspark-notebook
      container_name: jupyter-notebook
      ports:
        - "8888:8888"
      volumes:
        - ./src:/home/jovyan/work